# Application name
spring.application.name=rest-service

# Database settings
spring.datasource.url=jdbc:mariadb://localhost:3306/growandcheer
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# HikariCP settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080

# Disable Spring Security auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# application.properties
jwt.secret=MySuperSecretKeyThatIsVeryLongAndSecure1234567890
jwt.expiration=604800
#604800 untuk membuat dia token jangka panjang 604800 detik = 7 hari
